The following message-combo is a bind I made for people like you:
Please stop saying that people are 'hacking'. I probably know what you are trying to say, but please hear me out.
Calling these people 'hackers' is giving them too much credit. They are 'cheaters' at most and should be reffered to as such.
The reason for this is, that hacking includes coding yourself and litterally hacking yourself through a system.
For cheating on the other hand one doesn't need no special skills like that.
Cheating reffers to a way of playing that is not allowed and illegitemate. Downloading a script to be better is not 'hacking'.
It is cheating. I'd like people to know this and clear up this common misconception.
