This script is here to answer the question whether I cheat or in what way these scripts work. Oh and if it's cheating/illegal.
So, first of: these messages are sent using an external program, but *not* by a cheat.
The tool uses the developer intended "rcon" feature to interface the console of this tf2 instance to execute tf2 commands.
The commands are just basic "say <message>" commands chained together with a cooldown.
Since these tools are actually intended for use like this (mostly for servers though), it is completely legal.
The tool uses features of the game as intended.
If that wouldn't be the case, it would be illegal to bind actions (like jumping) to other buttons as well (and chatting too).
Hope that answered the questions you may or may not have had.
