The following message-combo is a bind I made for people like you:
I noticed that you accused a player in chat of cheating in some way or another.
I know this might be hard to understand, but I do not tend to trust randoms over my own eyes.
That's why I will need to take a look and gather evidence by spectating the suspect myself.
I will not support kicking random players because someone is mad or something.
If I happen to see the suspect using cheats, I will take actions and try to kick.
Also Note: Checking might take a minute or two, especially if they are hiding the cheats now.
(Cheaters who have been called out in chat are usually aware of the suspicions and therefore temporarily disable their cheats.)
That's why I will keep spectating them every now and then, even if I find nothing suspicious now.
TLDR: I won't kick innocents, let me take a look at <suspicious_person> first.
